- name: Ensure nginx is installed
  become: yes
  apt: name=nginx state=present

- name: Setup renewal for certs
  become: yes
  cron: name="certbot renewal" job="/usr/bin/certbot-auto renew" hour=1 minute=0 weekday=1

- name: Setup reloading of server after renewal
  become: yes
  cron: name="nginx reload" minute="05" hour="1" weekday="1" job="/etc/init.d/nginx reload"

- name: Create certificate
  become: yes
  shell: /usr/bin/certbot-auto certonly --force-renew --webroot --webroot-path=/usr/share/nginx/html --email {{ emailforencryption }} --agree-tos -d {{ urls.api }}

- name: Copy passwd file
  become: yes
  copy: content={{password_for_nginx}} dest=/etc/nginx/sites-available/.htpasswd

- name: Copy https nginx config
  become: yes
  template: src={{service}}.https.conf dest=/etc/nginx/sites-available/{{service}}.https.conf mode=0644 force=yes

- name: Add symlink to sites-enabled
  become: yes
  file: src=/etc/nginx/sites-available/{{service}}.https.conf dest=/etc/nginx/sites-enabled/{{service}}.https state=link
  notify:
    - Restart Nginx