- name: Install dependencies
  apt: name={{ item }} state=latest
  become: yes
  with_items:
    - python
    - python-dev
    - gcc
    - dialog
    - libaugeas0
    - augeas-lenses
    - libssl-dev
    - libffi-dev
    - ca-certificates
    - python-pip
    - python-virtualenv
    - git
    - libpython-dev
    - zlib1g-dev

- name: Get certbot
  become: yes
  get_url: url="https://dl.eff.org/certbot-auto" dest=/usr/bin

- name: Set certbot mode
  become: yes
  file: path=/usr/bin/certbot-auto mode=0750

- name: Ensure webroot exists
  become: yes
  file: path=/var/www/well-known state=directory mode=0755