- name : Add ssh to ubuntu firewall
  become: yes
  command: /usr/sbin/ufw allow ssh
  register: command_result
  changed_when: "'Rules updated' in command_result.stdout"

- name: Allow http and https
  become: yes
  command: /usr/sbin/ufw allow 80,443/tcp
  register: command_result
  changed_when: "'Rules updated' in command_result.stdout"

- name: Enable ufw
  become: yes
  command: /usr/sbin/ufw enable